### ISSUE TITLE
Unify the margins of the main container in the single member's profile 

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/community-web#112]
The margin bottom of the container for instance, should be the same as its margin top, right, and left. 

![Screenshot 2022-11-20 at 16-25-23 JOSA Community](https://user-images.githubusercontent.com/79845228/202904621-8d9c0fe3-02fa-4c0e-b4c9-52bba2634eb9.png)

**Comment by itsmohmans** [comment]
I think this issue was just in the details container (the one in the screenshot above). It should be fixed now in #125.
