### ISSUE TITLE
The location icon in member's profile is not aligned well with the text next to it

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/community-web#124]
![Screenshot 2022-11-21 at 19-17-58 JOSA Community](https://user-images.githubusercontent.com/79845228/203105455-3bdb5382-64c3-4d1d-8a06-dd5d53d58f4d.png)

**Comment by itsmohmans** [comment]
This issue is a duplicate of #109. Resolved in #125.

**Comment by alsahawneh** [comment]
> This issue is a duplicate of #109. Resolved in #127.

Apologies, I didn't notice that the issue has been already opened by Issa. I'll therefore close this issue.  Thanks @itsmohmans

**Comment by thamudi** [comment]
@itsmohmans @alsahawneh please do not close any issues without referring to me first.
