### ISSUE TITLE
Bug in the member's filter

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/community-web#131]
After collapsing the filter and reopening it. If the page is showing non-member contributors, the checkbox will appear unchecked, which will cause confusion to users as the page is still showing contributors who are not members with their box being unchecked at the same time (see attached screenshot). 

Once checked, the checkbox should stay so unless the user unchecks it. 

![Screenshot_20221123_200504_org mozilla firefox](https://user-images.githubusercontent.com/79845228/203607970-5c446ff5-2d65-44f7-b0fb-0dcb88634943.jpg)

**Comment by thamudi** [comment]
@itsmohmans please follow up on this task
