### ISSUE TITLE
Bug in the sorting dropdown list

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/community-web#133]
The arrow of the sorting dropdown list in (the filter) sometime fails to load. I don't rightly know what might be causing this. 

![Screenshot 2022-11-23 at 20-26-41 JOSA Community](https://user-images.githubusercontent.com/79845228/203611294-0f58aa7d-f661-4656-8998-9a405d2e9078.png)

**Comment by itsmohmans** [comment]
How can you reproduce this?

**Comment by itsmohmans** [comment]
@thamudi @alsahawneh I still couldn't reproduce this issue
