### ISSUE TITLE
HeroBanner's image does not look as good as desired

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/community-web#137]
The HeroBanner's image does not look as good as could be desired, especially when it comes to medium-sized screens. 

![Screenshot 2022-11-27 at 15-13-35 JOSA Community](https://user-images.githubusercontent.com/79845228/204134882-be5cdf4c-949a-44b7-9016-704eed1fde1c.png)

![Screenshot 2022-11-27 at 15-13-10 JOSA Community](https://user-images.githubusercontent.com/79845228/204134883-cba8a3d2-bded-46fa-826a-54fd509ae293.png)

**Comment by thamudi** [comment]
Closed, stale issue
