### ISSUE TITLE
Autoscroll to the results once the filter is applied

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/community-web#138]
The filter reserves a large area in the mobile view (See attached screenshot). And therefore if a user, for instance, searches for a certain member's name, the website does so without the user knowing that their filter has been already applied since the filter component is covering the whole page. For a better user experience, the page should scroll automatically to the refined results once the filter is applied. 

![Screenshot 2022-11-27 at 16-28-55 JOSA Community](https://user-images.githubusercontent.com/79845228/204137998-0d1bbb05-bdb7-4632-87bd-5602b821eea0.png)

**Comment by thamudi** [comment]
@itsmohmans please follow up on this task
