### ISSUE TITLE
Feature: Create a member forgot password

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/community-web#151]
A password reset email is sent to the email address added or associated to the username.

 - [ ] Needs to forward the mail over to the user, checkout expressmailer or relevant packages

![image](https://user-images.githubusercontent.com/18720062/210359868-c6e509ee-08e8-4e50-a6cd-eeffee1817b3.png)

**Comment by itsmohmans** [comment]
> Needs to forward the mail over to the user, checkout expressmailer or relevant packages

is there an API endpoint to check if the email provided is connected to a user?

I'm currently working on this in [feature/forgot-password](https://github.com/jordanopensource/community-web/tree/feature/forgot-password)

**Comment by thamudi** [comment]
Done in PR #157
