### ISSUE TITLE
Feature: Create a User Widget

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/community-web#152]
As a logged-in user I should be able to see a widget with my profile picture in the menu bar, so I can know I am logged in and I can change settings related to my account.

- [x] A user widget with the profile picture is shown on the top-right of the menu.
- [x] A dropdown menu is visible to the user with her name, if the widget is clicked.
- [x] The user can click on 'Your Profile' to be redirected to her profile.
- [ ] The user can click on 'Settings' to be redirected to the settings page.
- [x] The user can click on 'Sign out' to sign out from [JOSA.community](http://josa.community/).
![image](https://user-images.githubusercontent.com/18720062/210360350-fe4b6556-62cb-4883-a82f-42c67d1c9028.png)
![image](https://user-images.githubusercontent.com/18720062/210360374-0f27701d-1883-4952-bfd4-c8f98e45f88d.png)

**Comment by mahasneh** [comment]
You can use the "sign-out" icon for sign out, rather than "power-off"
