### ISSUE TITLE
Search Members Functionality is broken

### ISSUE THREAD

**Issue by ahmadjehad** [jordanopensource/community-web#159]
**Describe the bug**
The search functionality is not working in two areas

- On the Register Page 

**To Reproduce**

1.    Go to https://josa.community/register
2.    Fill the text fields in the first 2 pages
3.    When reaching the Vouching page
4.    Try to search
5.    See the error

**Record**

https://user-images.githubusercontent.com/45077440/211535628-082dd8b9-3370-4afc-9202-5a0acd21eb79.mp4

---

- On the Members Page

**To Reproduce**

1.    Go to https://josa.community/members
2.    Scroll down to the search box
3.    Try to search
4.    See the error

**Record**

https://user-images.githubusercontent.com/45077440/211535684-051ab126-5ac6-45a9-9ef1-8271b44d7d97.mp4

**Expected behavior**
The search text field and filters should be working fine and display proper results related to the user input.

**Improvement**
In the register form the search bar is barely visible, it would be nice to have some style edits for better UI/UX

**Tested On:**
Desktop:
    OS: Windows 10
    Browser: Firefox
    Version: 108.0.2

**Comment by thamudi** [comment]
fixed on development release, awaiting production release

**Comment by thamudi** [comment]
These have been resolved in the dev-channel release.
Marking this as fixed, we should push this into production very soon.

@ahmadjehad Thank you for your contribution to raising this issue. I would suggest separating GitHub issues in the future even if they seem related.

**Comment by ahmadjehad** [comment]
Will do,
Are the new fixes merged to the production?
