### ISSUE TITLE
API server Proxy not working 

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/community-web#206]
Nuxt server proxy is unable to communicate with the backend on any level, which include but not limited to the following:

- Loging into the account
- Resetting the password
- Listing the members (Accessing the server proxy like querying non JOSA members)
- Updating the profile.

**Comment by mbaraa** [comment]
When a user clicks on reset password, they receive an email, but the API never responds, so the Nuxt client hangs on loading the response. 

[this](https://github.com/jordanopensource/community-web/blob/main/components/login/forgotPassword.vue#L75) line is making a request to the `/forgot-password/send-email` endpoint, which doesn't exist according to [this](https://github.com/jordanopensource/community-api/blob/development/src/auth/auth.controller.ts#L55)

**Comment by thamudi** [comment]
I tested the forgot password and it seems to be working fine. 

However, this issue still persists and its visible on the login page. 

After doing a small refactor for the login page to use the [nuxt-api-party](https://nuxt.com/modules/api-party) instead of native nuxt `$fetch`, it still didn't work. Which leads me to believe that it is a server issue.

The issue is reproducible in any api client like postman or insomnia.

## Steps to reproduce

- Create a josa membership submission and get approved. (Contact Tamim for confirmation)
- Reset password. (The request time might seem to take long, however, it's working fine)
- Try to login with the new password on the following endpoint `community.api/prod.josa.ngo/v2/auth/login`. 
- If you entered a wrong password, it will tell you that the password is not correct (which conclude that the API is working fine).
- If the password was correct it will take a long time before you will get the following response.

```html
<html>
  <head><title>504 Gateway Time-out</title></head>
  <body>
    <center><h1>504 Gateway Time-out</h1></center>
    <hr><center>nginx</center>
  </body>
</html>
```

## Conclusions

The issue seems to stem from Nginx and not the API or the web proxy.

Checking the API logs results in nothing.

Requesting @geokhoury or @thread-koder for additional help or insights on this matter.

**Comment by thamudi** [comment]
API gateway timeout was fixed by raising the CPU limit for the community api
