### ISSUE TITLE
Finalize member directory

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/community-web#84]
Fix the following in member dir
- [x] Make Card padding exact to container padding : 20px
- [x] Drop down Filter icon 
- [x] Add a nice loader instead of the loading text
- [x] Make the whole filter button clickable instead of the arrow on its own
- [x] Enhance the styling of the pagination arrows to match the desired design
- [x] Pagination bug on mobile: page numbers are missing
- [x] Pagination bug showing on mobile when there are no next page
- [x] Enhance the filter's arrow to match the desired design
- [x] Fix stylings that have been affected by global CSS

**NOTE:** Please write everything as tailwind classes from the start. If you face any issues refer to @thamudi

**Comment by alsahawneh** [comment]
@thamudi regarding the first task in this issue: we are talking about mobile view only, aren't we?

**Comment by thamudi** [comment]
yes

> @thamudi regarding the first task in this issue: we are talking about mobile view only, aren't we?

**Comment by thamudi** [comment]
@alsahawneh please rebased from development
`git rebase origin/development`
some changes were made to member dir styling and needs to be reflected.
Keep in mind that some styling are being overridden on the component level

**Comment by alsahawneh** [comment]
> 

Done
